project:
  name: PyPrac4_SimpleETLProject
  environment: dev

database:
  engine: sqlite
  path: /Users/willhager/Documents/Python Practice/PyPrac4_IngestionDB.db
  create_dirs: true

files:
  - name: Employees_1
    path: "MFGEmployees4.csv"
  - name: Employees_2
    path: "employee_data.csv"

logging:
  file: "pipeline.log"
  level: "INFO"